// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$UserModelImpl _$$UserModelImplFromJson(Map<String, dynamic> json) =>
    _$UserModelImpl(
      id: json['id'] as String,
      fullName: json['full_name'] as String?,
      phone: json['phone'] as String?,
      email: json['email'] as String?,
      photoUrl: json['photo_url'] as String?,
      bio: json['bio'] as String?,
      rating: (json['rating'] as num?)?.toDouble() ?? 5.0,
      totalRidesGiven: (json['total_rides_given'] as num?)?.toInt() ?? 0,
      totalRidesTaken: (json['total_rides_taken'] as num?)?.toInt() ?? 0,
      isAdmin: json['is_admin'] as bool? ?? false,
      isBanned: json['is_banned'] as bool? ?? false,
      setupComplete: json['setup_complete'] as bool? ?? false,
      fcmToken: json['fcm_token'] as String?,
      drivingExperience: json['driving_experience'] as String?,
      address: json['address'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
      vehicleModel: json['vehicle_model'] as String?,
      vehicleLicensePlate: json['vehicle_license_plate'] as String?,
      vehicleColor: json['vehicle_color'] as String?,
      vehicleType: json['vehicle_type'] as String?,
      docDrivingLicenseFront: json['doc_driving_license_front'] as String?,
      docDrivingLicenseBack: json['doc_driving_license_back'] as String?,
      docVehicleRc: json['doc_vehicle_rc'] as String?,
      docVerificationStatus:
          json['doc_verification_status'] as String? ?? 'not_submitted',
      docRejectionReason: json['doc_rejection_reason'] as String?,
      docReviewedAt: json['doc_reviewed_at'] == null
          ? null
          : DateTime.parse(json['doc_reviewed_at'] as String),
      idType: json['id_type'] as String?,
      idNumber: json['id_number'] as String?,
      idDocUrl: json['id_doc_url'] as String?,
      addressDocType: json['address_doc_type'] as String?,
      addressDocUrl: json['address_doc_url'] as String?,
      pincode: json['pincode'] as String?,
      state: json['state'] as String?,
      city: json['city'] as String?,
      tehsil: json['tehsil'] as String?,
      drivingLicenseNumber: json['driving_license_number'] as String?,
      pucNumber: json['puc_number'] as String?,
      insuranceNumber: json['insurance_number'] as String?,
      prefNoSmoking: json['pref_no_smoking'] as bool? ?? false,
      prefNoMusic: json['pref_no_music'] as bool? ?? false,
      prefNoHeavyLuggage: json['pref_no_heavy_luggage'] as bool? ?? false,
      prefNoPets: json['pref_no_pets'] as bool? ?? false,
      prefNegotiation: json['pref_negotiation'] as bool? ?? false,
    );

Map<String, dynamic> _$$UserModelImplToJson(_$UserModelImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'full_name': instance.fullName,
      'phone': instance.phone,
      'email': instance.email,
      'photo_url': instance.photoUrl,
      'bio': instance.bio,
      'rating': instance.rating,
      'total_rides_given': instance.totalRidesGiven,
      'total_rides_taken': instance.totalRidesTaken,
      'is_admin': instance.isAdmin,
      'is_banned': instance.isBanned,
      'setup_complete': instance.setupComplete,
      'fcm_token': instance.fcmToken,
      'driving_experience': instance.drivingExperience,
      'address': instance.address,
      'created_at': instance.createdAt.toIso8601String(),
      'updated_at': instance.updatedAt.toIso8601String(),
      'vehicle_model': instance.vehicleModel,
      'vehicle_license_plate': instance.vehicleLicensePlate,
      'vehicle_color': instance.vehicleColor,
      'vehicle_type': instance.vehicleType,
      'doc_driving_license_front': instance.docDrivingLicenseFront,
      'doc_driving_license_back': instance.docDrivingLicenseBack,
      'doc_vehicle_rc': instance.docVehicleRc,
      'doc_verification_status': instance.docVerificationStatus,
      'doc_rejection_reason': instance.docRejectionReason,
      'doc_reviewed_at': instance.docReviewedAt?.toIso8601String(),
      'id_type': instance.idType,
      'id_number': instance.idNumber,
      'id_doc_url': instance.idDocUrl,
      'address_doc_type': instance.addressDocType,
      'address_doc_url': instance.addressDocUrl,
      'pincode': instance.pincode,
      'state': instance.state,
      'city': instance.city,
      'tehsil': instance.tehsil,
      'driving_license_number': instance.drivingLicenseNumber,
      'puc_number': instance.pucNumber,
      'insurance_number': instance.insuranceNumber,
      'pref_no_smoking': instance.prefNoSmoking,
      'pref_no_music': instance.prefNoMusic,
      'pref_no_heavy_luggage': instance.prefNoHeavyLuggage,
      'pref_no_pets': instance.prefNoPets,
      'pref_negotiation': instance.prefNegotiation,
    };
